version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd!2023
      POSTGRES_DB: nest-realtor-plus-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
